from os import environ as env


DEBUG = env.get('RECOMMENDATION_ENV', 'development') == 'development'
KEY_PREFIX = env.get('RECOMMENDATION_KEY_PREFIX', 'query_')

EMBEDLY_API_KEY = env.get('EMBEDLY_API_KEY', '')
YAHOO_OAUTH_KEY = env.get('YAHOO_OAUTH_KEY', '')
YAHOO_OAUTH_SECRET = env.get('YAHOO_OAUTH_SECRET', '')

RECOMMENDATION_SERVICES = env.get('RECOMMENDATION_SERVICES')
if DEBUG and RECOMMENDATION_SERVICES:
    CELERY_BROKER_URL = 'redis://%s:6379/0' % RECOMMENDATION_SERVICES
    MEMCACHED_HOST = '%s:11211' % RECOMMENDATION_SERVICES
else:
    CELERY_BROKER_URL = env.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
    MEMCACHED_HOST = env.get('MEMCACHED_HOST', 'memcached:11211')
